f

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -58,10 +58,37 @@ jobs:
               exit 1
             fi
 
-            # Распаковка и восстановление бэкапа
-            unzip -o "$LATEST_BACKUP" -d /tmp/db_restore
-            docker exec -i finance_bot_test_postgres_1 psql -p "5432" -U "my_finance_bot" -d "my_finance_bot" < "$LATEST_BACKUP"
-            echo "Database restored successfully."
+            # Распаковка архива
+            RESTORE_DIR="/tmp/db_restore"
+            mkdir -p "$RESTORE_DIR"
+            unzip -o "$LATEST_BACKUP" -d "$RESTORE_DIR"
+
+            # Проверяем, что SQL файл существует
+            SQL_FILE=$(ls "$RESTORE_DIR"/*.sql | head -n 1)
+            if [ -z "$SQL_FILE" ]; then
+              echo "No SQL file found in the backup archive!"
+              exit 1
+            fi
+
+            # Ожидание запуска PostgreSQL
+            echo "Waiting for PostgreSQL to be ready..."
+            until docker exec finance_bot_test_postgres_1 pg_isready -h localhost -p 5432 -U my_finance_bot > /dev/null 2>&1; do
+              sleep 5
+            done
+            echo "PostgreSQL is ready."
+
+            # Восстановление из SQL файла
+            docker exec -i finance_bot_test_postgres_1 psql -p "5432" -U "my_finance_bot" -d "my_finance_bot" < "$SQL_FILE"
+            if [ $? -ne 0 ]; then
+              echo "Error occurred during database restoration!"
+              exit 1
+            fi
+
+            # Удаление временных файлов
+            echo "Cleaning up temporary files..."
+            rm -rf "$RESTORE_DIR"
+
+            echo "Database restored and temporary files removed successfully."
 
   # Продакшн сборка для ветки main
   production_build:
